export const
  CHANGE_READY = 'CHANGE_READY',
  CHANGE_STATUS = 'CHANGE_STATUS',
  CLEAR_CONTROL = 'CLEAR_CONTROL',
  CONTROL_PRESSED = 'CONTROL_PRESSED',
  PAUSE = 'PAUSE',
  PLAYING = 'PLAYING',
  UPDATE = 'UPDATE';
